/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5192.stu29184517.gui;

import fit5192.stu29184517.repository.entities.BuyOrder;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import fit5192.stu29184517.repository.entities.Commodity;
import fit5192.stu29184517.repository.entities.SaleOrder;
import fit5192.stu29184517.repository.entities.Types;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author luzhe
 */
public class GUIimpl extends javax.swing.JFrame {

    /**
     * Creates new form GUIimpl
     */
    public GUIimpl(ActionListener actionListener, ListSelectionListener listSelectionListener) {
        initComponents();
          // add action listeners
        //this.closeButton.addActionListener(actionListener);
        this.jButtonId.addActionListener(actionListener);
        this.jButtonTitle.addActionListener(actionListener);
        this.jButtonType.addActionListener(actionListener);
        this.jButtonViewAll.addActionListener(actionListener);
        this.jButtonClose.addActionListener(actionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        jButtonTitle = new javax.swing.JButton();
        jButtonType = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListType = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSale = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBuy = new javax.swing.JTable();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jButtonId = new javax.swing.JButton();
        jButtonViewAll = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Commodity ID", "Name", "Sale Quantity", "Sale Order", "Buy Quantity", "Buy Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableItem);

        jButtonTitle.setText("Search");

        jButtonType.setText("Search");

        jScrollPane2.setViewportView(jListType);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel1.setText("Types");

        jTableSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Commodity", "Quantity", "Price(per unit)", "Total Price"
            }
        ));
        jScrollPane3.setViewportView(jTableSale);

        jTableBuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Commodity", "Quantity", "Price(per unit)", "Total Price"
            }
        ));
        jScrollPane4.setViewportView(jTableBuy);

        jTextFieldTitle.setText("title");
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jTextFieldType.setText("type");
        jTextFieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeActionPerformed(evt);
            }
        });

        jTextFieldId.setText("id");
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonId.setText("Search");
        jButtonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdActionPerformed(evt);
            }
        });

        jButtonViewAll.setText("View All Item");

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonId))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonType)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonTitle)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonType)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewAll)
                    .addComponent(jButtonClose))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIdActionPerformed

    public void displayMessageInDialog(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void displayItemDetails( List<Commodity> commodities ) {  
        this.clearItemTable();
        for (Commodity commodity  : commodities) {
        ((DefaultTableModel)this.jTableItem.getModel()).addRow(new Object[]{commodity.getCommodityId(), commodity.getTitle(), commodity.getQuantityCirculation(), commodity.getSaleOrderNum(), commodity.getQuantity(), commodity.getBuyOrderNum()});    
        }
    }
    
    
      public void displayBuy( List<BuyOrder> orders,String name ) {  
         
        for (BuyOrder order  : orders) {
        ((DefaultTableModel)this.jTableBuy.getModel()).addRow(new Object[]{name, order.getQuantity(), order.getPerPrice(), order.getPrice()});    
        }
    }
    
      public void displaySale( List<SaleOrder> orders,String name ) {  
         
        for (SaleOrder order  : orders) {
        ((DefaultTableModel)this.jTableSale.getModel()).addRow(new Object[]{name, order.getQuantity(), order.getPerPrice(), order.getPrice()});    
        }
    }
      
      
     public void displayTypes( List<Types> types ) {  
        
        DefaultListModel dflm2 = new DefaultListModel();
        dflm2.clear();
        for (Types type  : types) {
            //System.out.println(type.getTypeName());  
        dflm2.addElement((String)type.getTypeName());    
        }
        this.jListType.setModel(dflm2);
    }
    
     private void clearTypeTable() {     
        ((DefaultListModel)this.jListType.getModel()).clear() ;
        
       
    }
    
    private void clearItemTable() {     
        
        
        int numberOfRow = this.jTableItem.getModel().getRowCount();
        
        if (numberOfRow > 0) {
            DefaultTableModel tableModel = (DefaultTableModel) this.jTableItem.getModel();
            for (int index = (numberOfRow - 1); index >= 0; index --) {
                tableModel.removeRow(index);
            }            
        }
        
        int numberOfRow1 = this.jTableBuy.getModel().getRowCount();
        
        if (numberOfRow1 > 0) {
            DefaultTableModel tableModel = (DefaultTableModel) this.jTableBuy.getModel();
            for (int index = (numberOfRow1 - 1); index >= 0; index --) {
                tableModel.removeRow(index);
            }            
        }
        
        int numberOfRow2 = this.jTableSale.getModel().getRowCount();
        
        if (numberOfRow2 > 0) {
            DefaultTableModel tableModel = (DefaultTableModel) this.jTableSale.getModel();
            for (int index = (numberOfRow2 - 1); index >= 0; index --) {
                tableModel.removeRow(index);
            }            
        }
    }
    
    
    public int getCommodityId(){
         String id = this.jTextFieldId.getText();
        return id == null || id.isEmpty() ? 0 : Integer.parseInt(id);
    }
    
    public String getCommodityTitle(){
         String title = this.jTextFieldTitle.getText();
         //System.out.println("title"); 
        // System.out.println(title); 
        return title == null || title.isEmpty() ? "worong" : title;
    }
    
    public String getCommodityType(){
         String type = this.jTextFieldType.getText();
          
         System.out.println(type); 
        return type == null || type.isEmpty() ? "worong" : type;
    }
    
    
    /**
      @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIimpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIimpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIimpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIimpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        // Create and display the form 
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIimpl().setVisible(true);
            }
        });
    }
    */



    public JButton getjButtonId() {
        return jButtonId;
    }


    public JButton getjButtonTitle() {
        return jButtonTitle;
    }


//    public JTable getjButtonType() {
//        return jButtonType;
//    }
    
    
     public JButton getjButtonType() {
        return jButtonType;
    }



    public JButton getjButtonViewAll() {
        return jButtonViewAll;
    }
    

    public JButton getjButtonClose() {
        return jButtonClose;
    }


 
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonId;
    private javax.swing.JButton jButtonTitle;
    private javax.swing.JButton jButtonType;
    private javax.swing.JButton jButtonViewAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBuy;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTable jTableSale;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
